name: Sonarqube scanner

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  sonar:
    runs-on: [self-hosted,ts-medium-x64-docker]

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
      - name: Fetch PR
        if: contains(github.ref, 'pull')
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: SonarQube Scan
        uses: tradeshift/actions-sonarqube@v2
        with:
          ca-cert: ${{ secrets.MTLS_CACERT }}
          client-cert: ${{ secrets.MTLS_CERT }}
          client-key: ${{ secrets.MTLS_KEY }}
          token: ${{ secrets.SONAR_TOKEN }}
          host: 'https://sonar.ts.sv'
